[package]
name = "deploy-code"
version.workspace = true
edition.workspace = true
description = "DeployCode 桌面客户端"

[lib]
name = "deploy_code_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
deploy-core.workspace = true
notify = "8.2.0"
