/** 新增 Nginx 配置时的默认模板（前端静态文案，与现有业务站点结构一致）。 */
export function defaultNginxTemplate(): string {
  return [
    "server {",
    "    listen 80;",
    "    server_name users.lefng.top;",
    "    root /usr/share/nginx/html/users-frontend/;",
    "    index index.html;",
    "",
    "    # 后端 API 转发 (general-plat 后端容器 user_svc_backend:8000)",
    "    location /api/ {",
    "        resolver 127.0.0.11 valid=30s;",
    '        set $backend "user_svc_backend";',
    "        proxy_pass http://$backend:8000;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "        proxy_read_timeout 300s;",
    "    }",
    "",
    "    # SPA路由支持",
    "    location / {",
    "        try_files $uri $uri/ /index.html;",
    "    }",
    "",
    "    # 静态资源缓存",
    "    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {",
    "        expires 1d;",
    '        add_header Cache-Control "public, max-age=86400";',
    "    }",
    "",
    "    # 禁止访问隐藏文件",
    "    location ~ /\\. {",
    "        deny all;",
    "        access_log off;",
    "        log_not_found off;",
    "    }",
    "",
    "    access_log /var/log/nginx/access.log;",
    "    error_log /var/log/nginx/error.log;",
    "}",
    "",
  ].join("\n");
}
